// Single source of truth for the *display* metadata (name/scores/description) of every
// named hand from The Mah Jong Player's Companion. The server (socket-handler.js) imports
// this same file to pair each entry with its scoring/distance logic, so the reference pages
// here and the live "named hands within reach" hint in Learning mode can never drift apart.

export const SHORT_LIST_HANDS = [
	{ name: 'Wriggly Snake', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus one of each Wind, with one of those 13 tiles doubled.' },
	{ name: 'Run, Pung & Pair', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus a pung of one of those numbers and a pair of another, all the same suit.' },
	{ name: 'Greta\'s Garden', winning: 1000, fishing: 400, description: 'A chow-run of 1-7 in one suit, plus one of each Wind and one of each Dragon.' },
	{ name: 'Greta\'s Dragon', winning: 1000, fishing: 400, description: 'A chow-run of 1-7 in one suit, plus one of each Wind and a pung of one Dragon.' },
	{ name: 'Gertie\'s Garter', winning: 1000, fishing: 400, description: 'A chow-run of 1-7 in one suit and another chow-run of 1-7 in a different suit.' },
	{ name: 'Red Lantern', winning: 2000, fishing: 800, description: 'A chow-run of 1-7 in one suit, plus a pung of your own Wind and a pung of Red Dragon.' },
	{ name: 'Gates of Heaven', winning: 1000, fishing: 400, description: 'A chow-run of 2-8 in one suit, plus a pung of 1s and a pung of 9s in that same suit.' },
	{ name: 'Confused Gates', winning: 1000, fishing: 400, description: 'A chow-run of 2-8 in one suit, plus a pung of 1s and a pung of 9s, each in a different suit.' },
	{ name: 'Windy Chow', winning: 500, fishing: 200, description: 'A chow in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Big Robert', winning: 500, fishing: 200, description: '(Best-effort reading, unconfirmed) A run of four consecutive numbers in each suit, plus a pair of a Wind or Dragon.' },
	{ name: 'Moon at Bottom of Well', winning: 1000, fishing: 400, description: 'A run of 1-9 in Dots, plus one more chow and a pair, all in Dots.' },
	{ name: 'Knitting', winning: 500, fishing: 200, description: 'Seven pairs of the same seven numbers, confined to two suits (each individual pair same-suited).' },
	{ name: 'Triple Knitting', winning: 500, fishing: 200, description: 'Four numbers, each held once in all three suits, plus a same-suit pair of a fifth number.' },
	{ name: 'All Pair', winning: 500, fishing: 200, description: 'Seven pairs of any tiles (Seven Pairs).' },
	{ name: 'All Pair Honours', winning: 1000, fishing: 400, description: 'Seven pairs, each a Wind, Dragon, or a suit terminal (1 or 9).' },
	{ name: 'Heavenly Twins', winning: 1000, fishing: 400, description: 'Seven pairs, all in one suit.' },
	{ name: 'Windfall', winning: 1000, fishing: 400, description: 'One of each Wind, plus five pairs of numbers in one suit.' },
	{ name: 'All Pair Ruby Jade', winning: 1000, fishing: 400, description: 'A pair of Green Dragon, a pair of Red Dragon, and five pairs from the red/green Bamboo numbers (1,2,3,4,5,6,7,8,9).' },
	{ name: 'Sparrow\'s Sanctuary', winning: 1500, fishing: 600, description: 'A kong of Bamboo 1s, plus a pair of each green Bamboo number (2, 3, 4, 6, 8).' },
	{ name: 'Windy Ones', winning: 1000, fishing: 400, description: 'A pung of 1s in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Windy Nines', winning: 1000, fishing: 400, description: 'A pung of 9s in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Hachi Ban', winning: 1000, fishing: 400, description: 'A run of 1-8 or 2-9 in one suit, plus a pair of each remaining Wind (three pairs) or a pair of each Dragon (three pairs).' },
	{ name: 'Four Blessings', winning: 1500, fishing: 600, description: 'A pung of each of the four Winds, plus any pair.' },
	{ name: 'Grand Sequence', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus a pung of a Wind or Dragon and a pair in any suit.' },
	{ name: 'Dragonfly', winning: 1000, fishing: 400, description: 'One of each Dragon, plus a pung in each of the three suits and a pair in any suit.' },
	{ name: 'Dragon\'s Breath', winning: 1000, fishing: 400, description: 'One of each Dragon with one doubled, plus five pairs of numbers in one suit.' },
	{ name: 'Wriggly Dragon', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus one of each Dragon with one Dragon tripled into a pung.' },
	{ name: 'Green Jade', winning: 1000, fishing: 400, description: 'A pung of Green Dragon, plus three pungs and a pair, all in Bamboo.' },
	{ name: 'Red Coral', winning: 1000, fishing: 400, description: 'A pung of Red Dragon, plus three pungs and a pair, all in Characters.' },
	{ name: 'White Opal', winning: 1000, fishing: 400, description: 'A pung of White Dragon, plus three pungs and a pair, all in Dots.' },
	{ name: 'Guardian Dragon', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus a pung of one Dragon and a pair of a different Dragon.' },
	{ name: 'Three Great Scholars', winning: 1500, fishing: 600, description: 'A pung of each of the three Dragons, plus a chow or pung and a pair, any suit.' },
	{ name: 'Unique Wonder', winning: 2000, fishing: 800, description: 'One of each Wind, each Dragon, and each suit terminal (1 and 9 in all three suits), with one of those 13 tiles doubled.' },
	{ name: 'Five Odd Honours', winning: 500, fishing: 200, description: 'A run of 1-9 in one suit, plus five different Winds/Dragons.' },
	{ name: 'Dragon\'s Tail', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus a pung of a Dragon and a pair of a Wind (or a pung of a Wind and a pair of a Dragon).' },
	{ name: 'Hovering Angel', winning: 1000, fishing: 400, description: 'A pung of your own seat Wind, plus a chow in each of the three suits and a pair of any Dragon.' }
];

// Hands added on top of the Short List above when a table plays Full List rules.
export const FULL_LIST_EXTRA_HANDS = [
	{ name: 'Guardian Winds', winning: 1000, fishing: 400, description: 'A run of 1-9 in one suit, plus a pung of one Wind and a pair of a different Wind.' },
	{ name: 'Dragon\'s Gates', winning: 1000, fishing: 400, description: 'A chow-run of 2-8 in one suit, plus a pung of that suit\'s matching terminal (1 or 9) and a pung of its matching Dragon (Characters-Red, Bamboo-Green, Dots-White).' },
	{ name: 'Dragon\'s Teeth', winning: 1000, fishing: 400, description: 'A chow-run of seven consecutive numbers in Characters or Dots, plus a pung of Red Dragon and a pung of White Dragon.' },
	{ name: 'Yin Yang', winning: 1000, fishing: 400, description: 'The tiles 1,1,2,3,4,5,5 in one suit and 5,5,6,7,8,9,9 in a different suit.' },
	{ name: 'Three Philosophers', winning: 1000, fishing: 400, description: 'A chow in each of the three suits, plus one more chow (or pung) and a pair, any suit.' },
	{ name: 'Chow Chow', winning: 500, fishing: 200, description: 'Four chows and a pair, all in one suit, won fully concealed and self-drawn off the last tile in the wall.' },
	{ name: 'Crazy Chows', winning: 500, fishing: 200, description: 'Four chows in any suits, plus a pair in any suit.' },
	{ name: 'Little Robert', winning: 500, fishing: 200, description: 'A chow in each of the three suits, plus a pung and a pair, any suit.' },
	{ name: 'Chop Suey', winning: 1000, fishing: 400, description: 'A 1-2-3 chow in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Chow Mien', winning: 1000, fishing: 400, description: 'A 7-8-9 chow in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Little Brother', winning: 500, fishing: 200, description: 'A chow in each of the three suits, plus a pair of your own seat Wind and one more chow in any suit.' },
	{ name: 'Apple Blossom', winning: 1000, fishing: 400, description: 'Three chows in any suits, plus a pung of White Dragon and a pair of Green Dragon.' },
	{ name: 'The Professors', winning: 500, fishing: 200, description: 'Three chows in any suits, plus one of each Dragon and a pair of your own seat Wind.' },
	{ name: 'Odds & Evens', winning: 1500, fishing: 600, description: 'Every odd number (1,3,5,7,9) in each of two suits, plus every even number (2,4,6,8) in the third suit.' },
	{ name: 'Heads and Tails', winning: 1000, fishing: 400, description: 'A pung of each suit\'s 1s and each suit\'s 9s (four pungs total), plus a pair of one more terminal.' },
	{ name: 'Robin', winning: 500, fishing: 200, description: 'A chow in one suit, two chows in a second suit, and a chow plus a pair in a third suit.' },
	{ name: 'All Pair Jade', winning: 1000, fishing: 400, description: 'A pair (or kong) of Green Dragon, plus pairs of every green Bamboo number (2, 3, 4, 6, 8).' },
	{ name: 'Imperial Jade', winning: 2000, fishing: 800, description: 'A pung of Green Dragon, plus three pungs of Bamboo numbers (or two pungs and one chow), and a pair of a green Bamboo number.' },
	{ name: 'Lily of the Valley', winning: 2000, fishing: 800, description: 'A pung of Green Dragon and a pung of White Dragon, plus two pungs of Bamboo numbers and a pair of a green Bamboo number.' },
	{ name: 'Red Lily', winning: 2000, fishing: 800, description: 'A pung of Red Dragon and a pung of White Dragon, plus two pungs of Bamboo numbers and a pair of a red Bamboo number.' },
	{ name: 'Royal Ruby', winning: 2000, fishing: 800, description: 'A pung of Red Dragon, plus three pungs of Bamboo numbers and a pair of a red Bamboo number.' },
	{ name: 'Ruby Jade', winning: 1000, fishing: 400, description: 'A pung of Red Dragon and a pung of Green Dragon, plus two pungs of Bamboo numbers and a pair of a red or green Bamboo number.' },
	{ name: 'Lillypilly', winning: 1000, fishing: 400, description: 'A pung of Green Dragon and a pair of White Dragon, plus three pungs of Dots numbers.' },
	{ name: 'Blue Mountains', winning: 1000, fishing: 400, description: 'A pung of Green Dragon, plus three pungs of Dots numbers and a pair of a blue-circle Dots number (2, 3, 4, 5, 8, 9).' },
	{ name: 'White Elephant', winning: 1000, fishing: 400, description: 'A pung of White Dragon, plus three pungs of Dots numbers and a pair of an even Dots number.' },
	{ name: 'Driven Snow', winning: 1000, fishing: 400, description: 'A pung of White Dragon, plus three pungs of Characters numbers and a pair of an odd Characters number.' },
	{ name: 'Dragon\'s Scales', winning: 1000, fishing: 400, description: 'A pung of Red Dragon, plus three pungs of Characters numbers and a pair of an even Characters number.' },
	{ name: 'Dragonette', winning: 1000, fishing: 400, description: 'One of each Wind, plus one of each Dragon with one Dragon doubled, and three pairs of non-terminal numbers (2-8) in one suit.' },
	{ name: 'Dragon\'s Run', winning: 1500, fishing: 600, description: 'A run of 1-9 in one suit, plus one of each Dragon and a pair of any Wind.' },
	{ name: 'Sunrise', winning: 1000, fishing: 400, description: 'A pung of East Wind and a pair of White Dragon, plus a pung using only numbers 2-8 in each of the three suits.' },
	{ name: 'Sunset', winning: 1000, fishing: 400, description: 'A pung of West Wind and a pair of Red Dragon, plus a pung using only numbers 2-8 in each of the three suits.' },
	{ name: 'Numbers in Parallel', winning: 1500, fishing: 600, description: 'A pung of one Wind/Dragon and a pair of a different Wind/Dragon, plus the same non-terminal number (2-8) pung\'d in all three suits.' },
	{ name: 'Numbers Doubled', winning: 1500, fishing: 600, description: '(Best-effort reading, unconfirmed) A pair of a Wind/Dragon, plus two different non-terminal numbers, each pung\'d in two different suits.' },
	{ name: 'Chinese Odds', winning: 1500, fishing: 600, description: 'A pair of one odd number, plus pungs of three other odd numbers, all in one suit.' },
	{ name: 'Seven Twins', winning: 500, fishing: 200, description: 'Seven pairs of any tiles (All Pair\'s shape), won fully concealed and self-drawn off the last tile in the wall.' },
	{ name: 'Golden Gates', winning: 1000, fishing: 400, description: 'Pairs of the even numbers 2, 4, 6, 8 in one suit, plus a pung of that suit\'s matching terminal (1 or 9) and a pung of its matching Dragon.' },
	{ name: 'Windy Dragons', winning: 1000, fishing: 400, description: 'A pair of each of the four Winds, plus a pung of two different Dragons.' },
	{ name: 'Windvane', winning: 1000, fishing: 400, description: 'One of each Wind with one doubled, plus a pung of one number in each of the three suits.' },
	{ name: 'Three Sisters', winning: 1000, fishing: 400, description: 'A pung of 3s in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Seven Brothers', winning: 1000, fishing: 400, description: 'A pung of 7s in each of the three suits, plus one of each Wind, with one Wind doubled.' },
	{ name: 'Civil War', winning: 1500, fishing: 600, description: 'A pung of North Wind and a pung of South Wind, plus the numbers 1, 1, 6, 8 in one suit and 1, 5, 6, 8 in a different suit.' },
	{ name: 'Up You Go', winning: 2000, fishing: 800, description: 'A concealed kong of 8s in one suit, plus one of each Wind, a single 2, a pair of 4s, a pung of 6s, and the kong of 8s in that suit (2, 4-4, 6-6-6, 8-8-8-8).' },
	{ name: 'Down You Go', winning: 2000, fishing: 800, description: 'A concealed kong of 2s in one suit, plus one of each Wind, and 2-2-2-2, 4-4-4, 6-6, and a single 8 in that suit.' },
	{ name: 'Red Waratah', winning: 1000, fishing: 400, description: 'A pung of Red Dragon and a pair of Green Dragon, plus a pung of a red Bamboo number, a pung in Dots, and a pung in Characters.' },
	{ name: 'All Winds and Dragons', winning: 1000, fishing: 400, description: 'A pair of one Wind or Dragon, plus a pung of four other different Winds/Dragons.' }
];

export const FULL_LIST_HANDS = [...SHORT_LIST_HANDS, ...FULL_LIST_EXTRA_HANDS];
